ReportDefinitions:
- reportName: PTReceiptRegister
  decryptionPathId: PTReceiptRegister
  summary: Report is used for audit, day-end, and year-end finance reconciliation activities 
  version: 1.0.0
  moduleName: pt-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  - name: name
    label: reports.pt.consumername
    type: string
    source: pt
    total: false
  - name: user_uuid
    label: reports.pt.user_uuid
    type: string
    source: pt
    showColumn: false 
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: true
  - name: payerName
    label: reports.pt.payerName
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: chequeNo
    label: reports.pt.chequeNo
    type: string
    source: pt
    total: false

  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: receiptstatus
    label: receiptstatus
    type: singlevaluelist
    pattern: 'list://NEW:New,DEPOSITED:Deposited,DISHONOURED:Dishonoured'
    source: pt
    isMandatory: false
    searchClause: AND ep.paymentstatus = $receiptstatus
  - name: collectorname
    label: reports.pt.collectorname
    type: singlevaluelist
    pattern: http://egov-hrms:8080/egov-hrms/employees/_search?tenantId=$tenantid&roles=PT_CEMP|$.Employees[*].user.id|$.Employees[*].user.name
    source: pt
    wrapper: true
    isMandatory: false
    searchClause: AND ep.createdby= $collectorname   
  query: |
        SELECT receiptnumber,payerName,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,users.name as name,users.uuid as user_uuid,
        transactionnumber,totalamountpaid AS amountCollected,ep.instrumentnumber as chequeNo,ROW_NUMBER() OVER(PARTITION BY receiptnumber) AS RowNum FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid JOIN egcl_bill as bill on ed.billid=bill.id JOIN eg_pt_property as property on bill.consumercode=property.propertyid JOIN eg_pt_owner as owner on property.id=owner.propertyid  JOIN eg_user as users on owner.userid=users.uuid where 1=1  and ed.businessservice='PT' and ep.paymentstatus !='CANCELLED' and ep.tenantid=$tenantid and owner.status='ACTIVE' and property.status='ACTIVE'
  orderby: order by ed.receiptdate desc

- reportName: PTCollectionReport
  decryptionPathId: PTCollectionReport
  summary: It helps administrators track the collection in the ULB and the employee collection performance. 
  version: 1.0.0
  moduleName: pt-reports
  sourceColumns:
  - name: locality
    label: reports.pt.locality
    type: string
    source: pt
    total: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
  - name: name
    label: reports.pt.collectorname
    type: string
    source: pt
    total: false
  - name: user_uuid
    label: reports.pt.user_uuid
    type: string
    source: pt
    showColumn: false
  - name: paymentinstrument
    label: reports.pt.paymentinstrument
    type: string
    source: pt
    total: false
  - name: totaltransactions
    label: reports.pt.totaltransactions
    type: string
    source: pt
    total: false  
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: true
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: locality
    label: reports.pt.locality
    type: singlevaluelist
    pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=$tenantid|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.code
    source: pt
    wrapper: true
    isMandatory: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
    searchClause: AND ptd.locality = $locality  
  - name: paymentinstrument
    label: paymentinstrument
    type: singlevaluelist
    pattern: 'list://CASH:CASH,CARD:CARD,DD:DD,CHEQUE:CHEQUE'
    source: pt
    isMandatory: false
    searchClause: AND paymentmode = $paymentinstrument  
  query: |
        SELECT ptd.locality AS locality, users.name as name,users.uuid as user_uuid, count(*) as totaltransactions,sum(totalamountpaid) AS amountCollected,paymentmode AS paymentinstrument FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid JOIN egcl_bill  as bill on ed.billid=bill.id JOIN eg_pt_property as property on bill.consumercode=property.propertyid JOIN eg_pt_address as ptd on property.id=ptd.propertyid JOIN eg_user as users on ep.createdby::int=users.id JOIN eg_userrole_v1 as userrole on users.id=userrole.user_id  where 1=1  and ed.businessservice='PT' and ep.paymentstatus !='CANCELLED' and ep.tenantid=$tenantid and userrole.role_tenantid=$tenantid and ep.paymentmode!='ONLINE' and userrole.role_code='PT_CEMP' and property.status='ACTIVE'
  groupby: group by locality,name,paymentinstrument,user_uuid

- reportName: DefaulterReport
  decryptionPathId: DefaulterReport
  summary: Report is usually generated weekly/monthly to send notice to the defaulters and used only in the demand-based systems.
  version: 1.0.0
  moduleName: pt-reports
  sourceColumns:
  - name: propertyid
    label: reports.pt.propertyid
    type: string
    source: pt
    total: false
  - name: name
    label: Owner Name
    type: string
    source: pt
    total: false
  - name: mobilenumber
    label: Mobile Number
    type: string
    source: pt
    total: false
  - name: guardian
    label: Father's Name
    type: string
    source: pt
    total: false
  - name: locality
    label: Locality
    type: string
    source: pt
    total: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
  - name: taxDue
    label: Tax Due
    type: string
    source: pt
    total: true
  - name: taxDueYear
    label: FY Wise Due Tax
    type: string
    source: pt
    showColumn: false
  searchParams:
  - name: locality
    label: reports.pt.locality
    type: singlevaluelist
    pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=$tenantid|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.code
    source: pt
    wrapper: true
    isMandatory: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
    searchClause: AND locality = $locality
  - name: usagetype
    label: reports.pt.usagetype
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=PropertyTax&masterName=UsageCategory&filter=%24.%2A%5B%3F%28%40.code%20%3D~%20%2F%5BA-Z%5D%2A%5C.%5BA-Z%5D%2A%5C.%5BA-Z%5D%2A%5C.%5BA-z%5D%2A%2F%29%5D|$.MdmsRes.PropertyTax.UsageCategory.*.code|$.MdmsRes.PropertyTax.UsageCategory.*.name
    source: pt
    wrapper: true
    isMandatory: false
    localisationPrefix: PROPERTYTAX_BILLING_SLAB_
    isLocalisationRequired: false
    searchClause: AND usagecategory = $usagetype
  query: |
        select * from (SELECT  property.propertyid, usr.name as name, usr.mobilenumber as mobilenumber,(CASE WHEN usr.guardianrelation LIKE 'FATHER' THEN usr.guardian ELSE 'NULL' END) as guardian, property.usagecategory, locality  FROM EG_PT_PROPERTY property INNER JOIN EG_PT_ADDRESS address ON property.id = address.propertyid INNER JOIN EG_PT_OWNER owner ON property.id = owner.propertyid INNER JOIN eg_user usr ON owner.userid=usr.uuid  LEFT OUTER JOIN EG_PT_UNIT unit ON property.id =  unit.propertyid  WHERE  property.tenantId=$tenantid AND owner.status = 'ACTIVE' AND property.status = 'ACTIVE') as propertydata LEFT OUTER JOIN (select consumercode,sum(taxdue) as taxDue, STRING_AGG(year || '(Rs.' || taxdue || ')',',')  as taxDueYear from ( select d.consumercode, (to_char((To_timestamp(d.taxperiodfrom/1000) at time Zone 'Asia/Kolkata'),'YYYY') || '-' || to_char((To_timestamp(d.taxperiodto/1000) at time Zone 'Asia/Kolkata'),'YY')) as year ,  sum(dd.taxamount)-sum(dd.collectionamount) as taxdue from egbs_demanddetail_v1 dd, egbs_demand_v1 d where dd.demandid=d.id and d.status!='CANCELLED' and dd.tenantid=$tenantid and d.tenantid=$tenantid and (to_char((To_timestamp(d.taxperiodfrom/1000) at time Zone 'Asia/Kolkata'),'YYYY') || '-' || to_char((To_timestamp(d.taxperiodto/1000) at time Zone 'Asia/Kolkata'),'YY')) != '2023-24' group by d.consumercode,(to_char((To_timestamp(d.taxperiodfrom/1000) at time Zone 'Asia/Kolkata'),'YYYY') || '-' || to_char((To_timestamp(d.taxperiodto/1000) at time Zone 'Asia/Kolkata'),'YY'))) tax where taxDue>0 group by tax.consumercode) as taxdata on propertydata.propertyid=taxdata.consumercode
  orderby: order by taxDue desc