---
ReportDefinitions:
  - reportName: AssetapplicationReport
    decryptionPathId: AssetapplicationReport
    summary: Asset Application Report
    version: 1.0.0
    moduleName: rainmaker-asset
    sourceColumns:
      - name: AssetUniqueID
        label: Asset Unique ID
        type: string
        source: asset
        total: true
      - name: AssetClassification
        label: Asset Classification
        type: string
        source: asset
        total: false
      - name: parentcategory
        label: Parent Category
        type: string
        source: asset
        total: false
      - name: AssetStatus
        label: Asset Status
        type: string
        source: asset
        isLocalisationRequired: true
        total: false
      - name: Department
        label: Department
        type: string
        source: asset
        total: false
        showColumn: false
      - name: FinancialYear
        label: Financial Year
        type: string
        source: asset
        total: false
      - name: createdtime
        label: Created Time
        type: string
        source: asset
        showColumn: false

    searchParams:
      - name: parentcategory
        label: Parent Category
        type: singlevaluelist
        source: asset
        isMandatory: false
        pattern: "list://Land:Land,Building:Building,Service:Service,IT:IT,Vehicle:Vehicle,Other:Other"
        searchClause: AND parentcategory = $parentcategory
      - name: AssetUniqueID
        label: Application Number
        type: string
        source: obps
        isMandatory: false
        searchClause: AND bp.applicationno = $applicationNo
      - name: fromDate
        label: FromDate
        type: epoch
        source: asset
        isMandatory: false
        searchClause: AND createdtime >= $fromDate
      - name: toDate
        label: ToDate
        type: epoch
        source: asset
        isMandatory: false
        searchClause: AND createdtime <= $toDate
      - name: financialyear
        label: Financial Year
        type: string
        source: asset
        isMandatory: false
        searchClause: AND createdtime <= $toDate

    query: SELECT applicationno AS AssetUniqueID, 
      classification AS AssetClassification, 
      parentcategory, 
      name AS Assetname, 
      status AS AssetStatus, 
      Department, 
      financialyear AS FinancialYear, 
      createdtime
      FROM eg_asset_assetdetails
