---
ReportDefinitions:
  - reportName: AssetapplicationReport
    decryptionPathId: ObpsDailyCollectionReport
    summary: Asset Application Report
    version: 1.0.0
    moduleName: rainmaker-asset
    sourceColumns:
      - name: applicationno
        label: Application No
        type: string
        source: asset
        total: true
      - name: AssetClassification
        label: Asset Classification
        type: string
        source: asset
        total: false
      - name: parentcategory
        label: Parent Category
        type: string
        source: asset
        total: false
      - name: AssetStatus
        label: Asset Status
        type: string
        source: asset
        isLocalisationRequired: true
        total: false
      - name: Department
        label: Department
        type: string
        source: asset
        total: false
        showColumn: false
      - name: FinancialYear
        label: Financial Year
        type: string
        source: asset
        total: false
      - name: createdtime
        label: Created Time
        type: string
        source: asset
        showColumn: false
    searchParams:
      - name: applicationno
        label: Application Number
        type: string
        source: asset
        isMandatory: false
        searchClause: AND b.applicationno = $applicationno
      - name: fromDate
        label: FromDate
        type: epoch
        source: asset
        isMandatory: true
        searchClause: AND b.createdtime >= $fromDate
      - name: toDate
        label: ToDate
        type: epoch
        source: asset
        isMandatory: true
        searchClause: AND b.createdtime <= $toDate

    query: 
      SELECT b.applicationno AS applicationno, 
      b.classification AS AssetClassification, 
      b.parentcategory as parentcategory, 
      b.name AS Assetname, 
      b.status AS AssetStatus, 
      b.Department as Department, 
      b.financialyear AS FinancialYear, 
      b.createdtime as createdtime
      FROM eg_asset_assetdetails b
      where 1=1
    
