---
ReportDefinitions:
  - reportName: AssetapplicationReport
    decryptionPathId: ObpsDailyCollectionReport
    summary: Asset Application Report
    version: 1.0.0
    moduleName: rainmaker-asset
    sourceColumns:
      - name: applicationno
        label: Application No
        type: string
        source: asset
        total: false
      - name: AssetClassification
        label: Asset Classification
        type: string
        source: asset
        total: false
      - name: parentcategory
        label: Parent Category
        type: string
        source: asset
        total: false
      - name: AssetStatus
        label: Asset Status
        type: string
        source: asset
        isLocalisationRequired: true
        total: false
      - name: Department
        label: Department
        type: string
        source: asset
        total: false
      - name: FinancialYear
        label: Financial Year
        type: string
        source: asset
        total: false
      - name: createdtime
        label: Created Time
        type: string
        source: asset
        showColumn: false
    searchParams:
      - name: applicationno
        label: Application Number
        type: string
        source: asset
        isMandatory: false
        searchClause: AND b.applicationno = $applicationno
      - name: fromDate
        label: FromDate
        type: epoch
        source: asset
        isMandatory: true
        searchClause: AND b.createdtime >= $fromDate
      - name: toDate
        label: ToDate
        type: epoch
        source: asset
        isMandatory: true
        searchClause: AND b.createdtime <= $toDate
    query: >
      SELECT 
        b.applicationno AS applicationno,
        b.bookrefno AS bookrefno,
        b.classification AS AssetClassification, 
        b.parentcategory AS parentcategory, 
        b.name AS Assetname, 
        b.status AS AssetStatus,
        CONCAT('COMMON_MASTERS_DEPARTMENT_', b.department) AS Department,
        b.financialyear AS FinancialYear, 
        b.createdtime AS createdtime 
        FROM 
        eg_asset_assetdetails b
        WHERE 
        1 = 1
  - reportName: AssetapplicationReportULBwise
    decryptionPathId: ObpsDailyCollectionReport
    summary: Asset Application Report
    version: 1.0.0
    moduleName: rainmaker-asset
    sourceColumns:
      - name: applicationno
        label: Application No
        type: string
        source: asset
        total: false
      - name: bookrefno
        label: Book Reference No
        type: string
        source: asset
        total: false
      - name: AssetClassification
        label: Asset Classification
        type: string
        source: asset
        total: false
      - name: parentcategory
        label: Parent Category
        type: string
        source: asset
        total: false
      - name: AssetStatus
        label: Asset Status
        type: string
        source: asset
        isLocalisationRequired: true
        total: false
      - name: Department
        label: Department
        type: string
        source: asset
        total: false
        isLocalisationRequired: true
      - name: tenantid
        label: tenantd
        type: string
        source: asset
        total: false
        showColumn: true
      - name: FinancialYear
        label: Financial Year
        type: string
        source: asset
        total: false
      - name: createdtime
        label: Created Time
        type: string
        source: asset
        showColumn: false
    searchParams:
      - name: applicationno
        label: Application Number
        type: string
        source: asset
        isMandatory: false
      - name: ulb
        label: ULB
        type: singlevaluelist
        source: asset
        wrapper: true
        isMandatory: false
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        searchClause: AND b.tenantid = $ulb     
      - name: fromDate
        label: FromDate
        type: epoch
        source: asset
        isMandatory: true
        searchClause: AND b.createdtime >= $fromDate
      - name: toDate
        label: ToDate
        type: epoch
        source: asset
        isMandatory: true
        searchClause: AND b.createdtime <= $toDate
    query: |
        SELECT 
        b.applicationno AS applicationno,
        b.bookrefno AS bookrefno,
        b.classification AS AssetClassification, 
        b.parentcategory AS parentcategory, 
        b.name AS Assetname, 
        b.status AS AssetStatus,
        CONCAT('COMMON_MASTERS_DEPARTMENT_', b.department) AS Department,
        b.financialyear AS FinancialYear, 
        b.createdtime AS createdtime, b.tenantid AS tenantid
        FROM 
        eg_asset_assetdetails b
        WHERE 
        1 = 1
    orderby: ORDER BY b.tenantId asc
