---
ReportDefinitions:
  - reportName: AssetapplicationReport
    decryptionPathId: AssetapplicationReport
    summary: Asset Application Report
    version: 1.0.0
    moduleName: rainmaker-asset
    sourceColumns:
      - name: AssetUniqueID
        label: Asset Unique ID
        type: string
        source: asset
        total: true
      - name: AssetClassification
        label: Asset Classification
        type: string
        source: asset
        total: false
      - name: parentcategory
        label: Parent Category
        type: string
        source: asset
        total: false
      - name: AssetStatus
        label: Asset Status
        type: string
        source: asset
        isLocalisationRequired: true
        total: false
      - name: Department
        label: Department
        type: string
        source: asset
        total: false
        showColumn: false
      - name: FinancialYear
        label: Financial Year
        type: string
        source: asset
        total: false
      - name: createdtime
        label: Created Time
        type: string
        source: asset
        showColumn: false

    query: SELECT applicationno AS AssetUniqueID, 
      classification AS AssetClassification, 
      parentcategory as parentcategory, 
      name AS Assetname, 
      status AS AssetStatus, 
      Department as Department, 
      financialyear AS FinancialYear, 
      createdtime as createdtime
      FROM eg_asset_assetdetails
