---
ReportDefinitions:
  - reportName: ApplicationStatusReport
    summary: Nummber of applications by there status
    version: 1.0.0
    moduleName: rainmaker-noc
    externalService:
      - entity: $.messages[*]
        apiURL: http://egov-localization:8080/localization/messages/v1/_search?locale=en_IN&tenantId=pg&module=rainmaker-noc
        keyOrder: code,message
        tableName: tbl_localization
    sourceColumns:
      - name: status
        label: report.nocdtl.status
        type: string        source: nocdtl
        total: false
      - name: total
        label: report.nocdtl.total
        type: string
        source: nocdtl
        total: true
      - name: tenantId
        label: report.noc.tenantid
        type: string
        source: noc
        total: false
    searchParams:
      - name: fromDate
        label: reports.nocdtl.fromDate
        type: epoch
        source: nocdtl
        isMandatory: false
        searchClause: AND nocdtl.lastmodifiedtime >= $fromDate
      - name: toDate
        label: reports.nocdtl.toDate
        type: epoch
        source: nocdtl
        isMandatory: false
        searchClause: AND nocdtl.lastmodifiedtime <= $toDate
      - name: ulb
        label: ULB
        type: singlevaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: noc
        wrapper: true
        isMandatory: false
        searchClause: AND noc.tenantId = $ulb      
    query: SELECT COUNT(applicationnumber) as total, status from eg_fn_firenocdetail
      nocdtl LEFT OUTER JOIN eg_fn_firenoc noc ON noc.uuid= nocdtl.firenocuuid
    groupby: GROUP BY status
