ReportDefinitions:
- reportName: StreetVendingReport
  decryptionPathId: StreetVendingReport
  summary: Report for street vending
  version: 1.0.0
  moduleName: sv-report
  sourceColumns:
  - name: svapplicationid
    label: applicationId
    type: string
    source: street-vending
    total: false
  - name: svcertificateno
    label: certificateNo
    type: string
    source: street-vending
    total: false
  - name: svapplicationstatus
    label: applicationStatus
    type: string
    source: street-vending
    total: false
  - name: svvendingactivity
    label: vendingActivity
    type: string
    source: street-vending
    showColumn: false 
  - name: svvendingzone
    label: vendingZone
    type: string
    source: street-vending
    total: true
  - name: vendorapplicationid
    label: vendorApplicationId
    type: string
    source: street-vending
    total: false
  - name: vendorname
    label: vendorName
    type: string
    source: street-vending
    total: false
  - name: addresslocality
    label: locality
    type: string
    source: street-vending
    total: false

  searchParams:
  - name: svapplicationstatus
    label: Application Status
    type: singlevaluelist
    pattern: 'list://APPLIED:Applied,APPROVED:Approved,REGISTRATIONCOMPLETED:Registration Completed,INSPECTIONPENDING:Inspection Pending,REJECTED:Rejected'
    source: street-vending
    isMandatory: false
    searchClause: AND sv.application_status = $svapplicationstatus
  # - name: svcertificateno
  #   label: Application Number
  #   type: string
  #   source: street-vending
  #   isMandatory: false
  #   searchClause: AND sv.certificate_no = $svcertificateno
 
  query: select sv.application_id as svapplicationid, sv.certificate_no as svcertificateno, sv.application_status as svapplicationstatus, sv.vending_activity as svvendingactivity, sv.vending_zone as svvendingzone, vendor.application_id as vendorapplicationid, vendor.name as vendorname, address.locality as addresslocality, address.locality_code as addresslocalitycode from eg_sv_street_vending_detail sv left join eg_sv_vendor_detail vendor on sv.application_id = vendor.application_id left join eg_sv_address_detail address on vendor.id = address.vendor_id where 1=1
