serviceMaps:
  serviceName: request-service
  mappings:
    - version: 1.0
      description: Persists water tanker application detail
      fromTopic: create-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_tanker_booking_details(booking_id, booking_no, tanker_type, tanker_quantity, water_quantity, description, delivery_date, delivery_time, extra_charge, vendor_id, vehicle_id, driver_id, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?::DATE, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.bookingNo
            - jsonPath: $.waterTankerBookingDetail.tankerType
            - jsonPath: $.waterTankerBookingDetail.tankerQuantity
            - jsonPath: $.waterTankerBookingDetail.waterQuantity
            - jsonPath: $.waterTankerBookingDetail.description
            - jsonPath: $.waterTankerBookingDetail.deliveryDate
            - jsonPath: $.waterTankerBookingDetail.deliveryTime
            - jsonPath: $.waterTankerBookingDetail.extraCharge
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_applicant_details(applicant_id, booking_id, name, mobile_number, gender, email_id, alternate_number, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail.applicantDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantName
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantMobileNo
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.gender
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantEmailId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantAlternateMobileNo
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_address_details(address_id, applicant_id, house_no, address_line_1, address_line_2, street_name, landmark, city, city_code, locality, locality_code, pincode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail.address
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.address.addressId
            - jsonPath: $.waterTankerBookingDetail.address.applicantId
            - jsonPath: $.waterTankerBookingDetail.address.houseNo
            - jsonPath: $.waterTankerBookingDetail.address.addressLine1
            - jsonPath: $.waterTankerBookingDetail.address.addressLine2
            - jsonPath: $.waterTankerBookingDetail.address.streetName
            - jsonPath: $.waterTankerBookingDetail.address.landmark
            - jsonPath: $.waterTankerBookingDetail.address.city
            - jsonPath: $.waterTankerBookingDetail.address.cityCode
            - jsonPath: $.waterTankerBookingDetail.address.locality
            - jsonPath: $.waterTankerBookingDetail.address.localityCode
            - jsonPath: $.waterTankerBookingDetail.address.pincode